"""add plans bind_vars and case details

Revision ID: fa5cc8952b39
Revises: 0026654debb2
Create Date: 2026-04-14 18:10:25.681775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa5cc8952b39'
down_revision: Union[str, None] = '0026654debb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bind_variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('data_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['tuning_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bind_variables_case_id'), 'bind_variables', ['case_id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=16), nullable=False),
    sa.Column('plan_hash', sa.String(length=32), nullable=True),
    sa.Column('plan_text', sa.Text(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('buffers', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['tuning_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_case_id'), 'plans', ['case_id'], unique=False)
    op.add_column('tuning_cases', sa.Column('title', sa.String(length=200), nullable=True))
    op.add_column('tuning_cases', sa.Column('category', sa.String(length=64), nullable=True))
    op.add_column('tuning_cases', sa.Column('sql_id', sa.String(length=32), nullable=True))
    op.add_column('tuning_cases', sa.Column('schema_name', sa.String(length=64), nullable=True))
    op.add_column('tuning_cases', sa.Column('instance_name', sa.String(length=64), nullable=True))
    op.add_column('tuning_cases', sa.Column('tuned_sql_text', sa.Text(), nullable=True))
    op.add_column('tuning_cases', sa.Column('rationale', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tuning_cases', 'rationale')
    op.drop_column('tuning_cases', 'tuned_sql_text')
    op.drop_column('tuning_cases', 'instance_name')
    op.drop_column('tuning_cases', 'schema_name')
    op.drop_column('tuning_cases', 'sql_id')
    op.drop_column('tuning_cases', 'category')
    op.drop_column('tuning_cases', 'title')
    op.drop_index(op.f('ix_plans_case_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_bind_variables_case_id'), table_name='bind_variables')
    op.drop_table('bind_variables')
    # ### end Alembic commands ###
